version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch
    container_name: os01
    restart: always
    environment:
      - cluster.name=opensearch-cluster
      - node.name=os01
      - discovery.seed_hosts=os01,os02
      - cluster.initial_master_nodes=os01,os02
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
#      - ./config/:/usr/share/opensearch/plugins/opensearch-security/securityconfig/
#    ports:
#      - 9200:9200
#      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch
    container_name: os02
    restart: always
    environment:
      - cluster.name=opensearch-cluster
      - node.name=os02
      - discovery.seed_hosts=os01,os02
      - cluster.initial_master_nodes=os01,os02
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards
    container_name: dashboards
    restart: always
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://os01:9200","https://os02:9200"]' # must be a string with no spaces when specified as an environment variable
    networks:
      - opensearch-net


  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.13.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "5514:5514/udp"
    expose:
      - "5044"
      - "5514/udp"
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
